import turtle
import time

def cuadrado(color, size=100):
	l.color(color)
	l.forward(1)
	l.forward(size)
	l.right(90)
	l.forward(size)
	l.right(90)
	l.forward(size)
	l.right(90)
	l.forward(size)

def cuadrado4(color1, color2, color3, color4, size=100):
	cuadrado(color1, size)
	cuadrado(color2, size)
	cuadrado(color3, size)
	cuadrado(color4, size)

turtle.setup(600,800)
l = turtle.Turtle()
l.shape ("turtle")
cuadrado4("red", "blue", "green", "orange", 150)
l.left(90)
l.forward(201)
cuadrado4("blue", "green", "orange", "red")
l.backward(350)
l.left(90)
l.forward(75)
l.left(90)
cuadrado("blue")
l.forward(250)
l.right(90)
cuadrado("blue")
l.backward(25)
l.left(90)
l.forward(225)
l.right(90)
cuadrado("blue")
l.forward(75)
l.left(90)
l.forward(300)
l.left(90)
l.forward(25)
l.right(90)
l.forward(45)
cuadrado("blue")
l.left(180)
l.forward(25)
l.right(90)
l.forward(45)
time.sleep(15)


